### ISSUE TITLE
Демо-приложение падает после ввода суммы.

### ISSUE THREAD

**Issue by pedrogarciyalopez** [yoomoney/yandex-checkout-android-sdk#41]
Демо-приложение падает после ввода суммы. Говорит: Caused by: com.yandex.metrica.impl.ob.qf: ApiKey is empty.
```
2020-01-13 15:55:37.173 10068-10068/ru.yandex.money.android.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.yandex.money.android.example, PID: 10068
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.yandex.money.android.example/ru.yandex.money.android.sdk.impl.CheckoutActivity}: com.yandex.metrica.impl.ob.qf: ApiKey is empty. Please, read official documentation how to obtain one: https://tech.yandex.com/metrica-mobile-sdk/doc/mobile-sdk-dg/concepts/android-initialize-docpage/
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.yandex.metrica.impl.ob.qf: ApiKey is empty. Please, read official documentation how to obtain one: https://tech.yandex.com/metrica-mobile-sdk/doc/mobile-sdk-dg/concepts/android-initialize-docpage/
        at com.yandex.metrica.impl.ob.qe.a(SourceFile:30)
        at com.yandex.metrica.impl.ob.kx.a(SourceFile:108)
        at com.yandex.metrica.impl.ob.kw.a(SourceFile:325)
        at com.yandex.metrica.YandexMetrica.getReporter(SourceFile:332)
        at ru.yandex.money.android.sdk.impl.metrics.YandexMetricaReporter.<init>(YandexMetricaReporter.kt:32)
        at ru.yandex.money.android.sdk.impl.AppModel.init$library_debug(AppModel.kt:272)
        at ru.yandex.money.android.sdk.impl.CheckoutInternal.tokenize$library_debug(CheckoutInternal.kt:106)
        at ru.yandex.money.android.sdk.impl.CheckoutActivity.tokenize(CheckoutActivity.kt:91)
        at ru.yandex.money.android.sdk.impl.CheckoutActivity.onCreate(CheckoutActivity.kt:57)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-01-13 15:55:37.200 10068-10068/ru.yandex.money.android.example I/Process: Sending signal. PID: 10068 SIG: 9
```

**Comment by Winner28** [comment]
Спасибо, приняли во внимание.

**Comment by Winner28** [comment]
Поправили
