### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Can not perform this action after onSaveInstanceState ru.yandex.money.android.sdk.impl.n$f.invoke

### ISSUE THREAD

**Issue by AdislanSaidov** [yoomoney/yandex-checkout-android-sdk#50]
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:11)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:26)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:65)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:87)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:1)
       at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(BottomSheetDialogFragment.java:7)
       at ru.yandex.money.android.sdk.impl.n$f.invoke(n.java:13)
       at ru.yandex.money.android.sdk.a.a$a.invoke(a.java:13)
       at ru.yandex.money.android.sdk.impl.b.run(b.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Устройство
Марка: Xiaomi
Модель: Redmi Note 7
Ориентация: Вертикальная
Свободная оперативная память: 770.43 MB
Свободное место на диске: 4.43 GB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой

**Comment by Winner28** [comment]
Спасибо, приняли во внимание

**Comment by Winner28** [comment]
Поправили
